PIH/openmrs-distro-pihemr

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
api/src/main/resources/messages_es.properties

https://tickets.pih-emr.org/browse/MEX-68

MEX-68: Fork primaryCare into a new component

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/apps/PatientRegistrationApp.java

https://tickets.pih-emr.org/browse/MEX-85
Also addresses [MEX-102](https://tickets.pih-emr.org/browse/MEX-102): PIH EMR should support multiple free-text address fields
@mogoodrich

MEX-85: Address should allow "Other" for community, with free text

---

api/src/main/java/org/openmrs/module/mirebalais/MirebalaisConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
api/src/main/resources/messages.properties
api/src/main/resources/messages_es.properties

https://tickets.pih-emr.org/browse/MEX-109

MEX-109: Add BP widget to patient dashboard

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

obsacrossencounters uses maxRecords not maxResults
latestobsforconcept has no limit parameter
Widget names all lowercase

Fix misuses of the widget API

---

api/src/main/resources/messages.properties

https://tickets.pih-emr.org/browse/MEX-157

MEX-157 No names for Mexico Clinic EncounterTypes

---

api/src/main/java/org/openmrs/module/mirebalais/MirebalaisConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderUtil.java
api/src/main/resources/messages.properties

https://tickets.pih-emr.org/browse/MEX-147

MEX-147: Should be easy to view patient diabetes clinical history

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

https://tickets.pih-emr.org/browse/MEX-158

MEX-158 Get rid of Mexico Clinic Initial Visit

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderUtil.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/apps/patientregistration/SectionsDefault.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/apps/patientregistration/SectionsMexico.java
api/src/main/resources/messages.properties

https://tickets.pih-emr.org/browse/MEX-149
I tried to create a new registration form section for "active casefinding" since it's not really demographic information, but I couldn't get the new section to appear. Not sure what I was missing. I've left it in Demographics for now.

MEX-149: Add boolean person attributes to Registration: immigrant, indigenous, active casefinding

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
api/src/main/resources/messages.properties

MEX-159 Combine all Mexico Clinic Visit form sections into one big sectionless form
https://tickets.pih-emr.org/browse/MEX-159

MEX-159 Combine all Mexico Clinic Visit form sections into one big sectionless form

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

MEX-207 Enable Mental Health program for CES
https://tickets.pih-emr.org/browse/MEX-207
Depends on https://github.com/PIH/openmrs-module-pihcore/pull/36
I added two components, MENTAL_HEALTH_FORM and MENTAL_HEALTH_PROGRAM, and composed MENTAL_HEALTH out of them.

MEX-207 Enable Mental Health program for CES

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

MEX-237 Create minimal Asthma program
https://tickets.pih-emr.org/browse/MEX-237
Depends on https://github.com/PIH/openmrs-module-pihcore/pull/38

MEX-237 Create minimal Asthma program

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

MEX-236 Create minimal Epilepsy program
https://tickets.pih-emr.org/browse/MEX-236
depends on https://github.com/PIH/openmrs-module-pihcore/pull/39

MEX-236 Create minimal Epilepsy program

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

MEX-208 Create/Enable Maternal Health program for CES
https://tickets.pih-emr.org/browse/MEX-208
depends on https://github.com/PIH/openmrs-module-pihcore/pull/41

MEX-208 Create/Enable Maternal Health program for CES

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/apps/patientregistration/SectionsHaiti.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/apps/patientregistration/SectionsMexico.java
api/src/main/resources/messages.properties

https://github.com/PIH/openmrs-module-pihcore/pull/43
depends on https://github.com/PIH/openmrs-module-pihcore/pull/43

MEX-119 Add CURP to Registration

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

https://tickets.pih-emr.org/browse/MEX-242
depends on https://github.com/PIH/openmrs-module-pihcore/pull/42

MEX-242 Create minimal Malnutrition program

---

README.md

https://tickets.pih-emr.org/browse/MEX-86
Document Address Hierarchy configuration changes

MEX-86 Address should have INEGI fields - EDO, MUN, LOC

---

README.md

Update README to include new site, JJ Dossen

LIB: Added JJ Dossen as facility supported

---

api/src/main/resources/messages.properties

https://tickets.pih-emr.org/browse/MEX-111
Add program names to messages.properties

MEX-111 Program names should display in Spanish

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

https://pihemr.atlassian.net/browse/MEX-314
Depends on https://github.com/PIH/openmrs-module-pihcore/pull/63

MEX-314 Switch CES from using MCH Program to ANC Program

---

api/src/main/java/org/openmrs/module/mirebalais/MirebalaisConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderUtil.java
api/src/main/resources/messages.properties

https://tickets.pih-emr.org/browse/MEX-270
Depends on https://github.com/PIH/openmrs-module-mirebalaismetadata/pull/21

MEX-270 Epilepsy dashboard should graph "# seizures in last month" over time, display baseline statically

---

api/src/main/java/org/openmrs/module/mirebalais/MirebalaisConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderUtil.java
api/src/main/resources/messages.properties

Also MEX-244 Add weight/height graph to Malnutrition dashboard
https://pihemr.atlassian.net/browse/MEX-243
https://pihemr.atlassian.net/browse/MEX-244

MEX-243 Add head circ graph to Malnutrition dashboard

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

MEX-121 Should be able to add CHW as relationship from dashboard
https://pihemr.atlassian.net/browse/MEX-121
Depends on https://github.com/PIH/openmrs-module-pihcore/pull/68

MEX-121 Should be able to add CHW as relationship from dashboard

---

api/src/main/java/org/openmrs/module/mirebalais/MirebalaisConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
api/src/main/resources/messages.properties

Fixup for https://pihemr.atlassian.net/browse/MEX-382 / https://github.com/PIH/openmrs-module-mirebalais/pull/56

Fix Asthma table for MEX-382

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/apps/GraphFactory.java

https://pihemr.atlassian.net/browse/MEX-362
Depends on https://github.com/PIH/openmrs-module-pihcore/pull/71

MEX-362 Height/weight graph on main patient dashboard

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
api/src/main/resources/messages.properties

https://pihemr.atlassian.net/browse/SL-88
Depends on https://github.com/PIH/openmrs-module-pihcore/pull/78

SL-88 Create new encounter type for Outpatient Visit

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/apps/patientregistration/SectionsSierraLeone.java
api/src/main/resources/messages.properties

Sets up occupation lists in SectionsSierraLeone and prepares for later addition of Ebola screening questions

Sl03mirebalais

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

https://pihemr.atlassian.net/browse/UHM-4026

UHM-4026 Hide Mental Health dashboard widgets for Haiti

---

api/src/main/java/org/openmrs/module/mirebalais/MirebalaisHospitalActivator.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/apps/patientregistration/SectionsDefault.java
omod/src/main/java/org/openmrs/module/mirebalais/page/controller/patientRegistration/AfterRegistrationPageController.java
omod/src/main/webapp/resources/styles/liberia.css
pom.xml

- Update registrationapp dependency version to1.15.0-SNAPSHOT
- Regex validation functionality for phone number
- Redirect to checkin after registration

LIB - Registration changes

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/apps/patientregistration/SectionsSierraLeone.java

@lnball and @mogoodrich  for your review.

add advice label for ebola questions and tb screening

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
api/src/main/resources/messages.properties

Add orders directly from Labs page

---

api/src/main/java/org/openmrs/module/mirebalais/MirebalaisHospitalActivator.java
omod/src/main/webapp/resources/scripts/liberia.js
omod/src/main/webapp/resources/styles/liberia.css

- CSS and JS for mental health section

 LIB - Epilepsy section within the Mental Health form - CSS and JS files

---

api/src/main/resources/liquibase.xml

@dmdesimone I'd appreciate your review of this code.  We can discuss in 2020.
https://pihemr.atlassian.net/browse/UHM-4200

UHM-4200 Mental Health program enrollment

---

api/src/main/resources/messages.properties

- i18n property for community health worker privileges

LIB - added i18n property for community health worker privileges

---

pom.xml

https://github.com/openmrs/openmrs-module-spa/releases/tag/spa-1.0.6

Bump spa version to 1.0.6

---

pom.xml

For https://pihemr.atlassian.net/browse/UHM-4458

Upgrade uicommons to snapshot version

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

https://pihemr.atlassian.net/browse/UHM-4499
depends on https://github.com/openmrs/openmrs-module-coreapps/pull/337

UHM-4499: Update dashboard widget to show the preferred concept names for dispensed drugs

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

Depends on https://github.com/PIH/openmrs-module-pihcore/pull/214

Add OVC form to CALF

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/apps/patientregistration/PatientRegistrationApp.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/apps/patientregistration/SectionsPeru.java

https://pihemr.atlassian.net/browse/PER-370
depends on https://github.com/PIH/openmrs-config-pihemr/pull/87

PER-370 Registration form - Level of Education section

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
api/src/main/java/org/openmrs/module/mirebalais/require/RequireUtil.java

Configure OVC program; don't show OVC forms for patient older than 21
Related to https://github.com/PIH/openmrs-config-pihemr/pull/88

UHM-4979 OVC Intake form pt 2

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

https://pihemr.atlassian.net/browse/PER-351
Depends on https://github.com/PIH/openmrs-module-pihcore/pull/217

Split up HIV component and COVID component. Create TB component.

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

seperate extension added for delivery

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

Made changes to module-mirebalais and module-pihcore to implement the TB program.
Depends on https://github.com/PIH/openmrs-module-pihcore/pull/224

TB Program configuration

---

README.md

This reflects the process that I have started to use to get my dev environments prepared.  It is slightly different that what we had been recommending.  A few comments:
* I think the process of first starting up with no modules is more robust, as it eliminates any errors in the logs, guesswork as to when one needs to stop the server to tweak the config, and issues that may crop up with incorrect metadata getting installed accidentally if the default configuration is incompatible with the final configuration.
* This includes the section on configuring the identifier generators from runtime properties, assuming we approve/merge this change I made from pihcore
* It add some additional information that may be helpful (need for a provider account, use of Docker)

Updates to dev setup for review

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/apps/patientregistration/SectionsDefault.java
omod/src/main/webapp/fragments/patientdashboard/encountertemplate/consultEncounterTemplate.gsp
omod/src/main/webapp/pages/login.gsp
omod/src/main/webapp/pages/mpi/findPatient.gsp
omod/src/main/webapp/pages/outpatientvitals/patient.gsp

https://issues.openmrs.org/browse/RA-1898
Spot checked a few in the UI, they look good.

RA-1898 Change all 'emr.' message codes to 'coreapps.' equivalents

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

https://pihemr.atlassian.net/browse/UHM-5315
Depends on https://github.com/PIH/openmrs-module-pihcore/pull/244
See also
https://github.com/PIH/openmrs-config-pihemr/pull/154
https://github.com/PIH/openmrs-config-zl/pull/72

UHM-5315 Add Clinical Note encounter type and form

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

https://pihemr.atlassian.net/browse/UHM-5315
See also https://github.com/PIH/openmrs-config-pihemr/pull/157

UHM-5315: Form should be called 'Comment'

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/apps/patientregistration/SectionsHaiti.java

https://pihemr.atlassian.net/browse/UHM-5369
Depends on https://github.com/openmrs/openmrs-module-registrationapp/pull/108

UHM-5369: Enable autcomplete for occupations widget in registration

---

api/src/test/java/org/openmrs/module/mirebalais/printer/impl/ZlEmrIdCardPrinterTest.java

https://pihemr.atlassian.net/browse/UHM-4354

Fix compilation for UHM-4354

---

README.md
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderUtil.java
pom.xml

Merging this will be dependent upon getting a few other prs in dependent projects merged in first.

UHM-5419: Move Programs from PIH Core to config-pihemr

---

pom.xml

https://pihemr.atlassian.net/browse/UHM-5276

Upgrade SPA Module to latest snapshot

---

distro/build-frontend.sh

https://pihemr.atlassian.net/browse/UHM-5276

Add validation to frontend build process

---

.gitignore
README.md
pihemrDeploy.sh

This is based on my comment in Jira here: https://pihemr.atlassian.net/browse/UHM-5505?focusedCommentId=118659 . This is approach (3), which I think is the best of them.

Have pihemrDeploy link in the site frontend config

---

distro/openmrs-distro.properties

Depends on https://github.com/PIH/openmrs-config-pihemr/pull/226

Add base frontend config

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

Fixes the problem which caused this reversion: https://github.com/PIH/openmrs-module-pihcore/commit/123419072b6a1a1f5701d498e438bdc3638809cf

Remove references to RelationshipTypeBundle (UHM-5559)

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
api/src/main/java/org/openmrs/module/mirebalais/require/RequireUtil.java

https://pihemr.atlassian.net/browse/UHM-5709

UHM-5709 Show Exposed Infant form for 18 months old and less

---

api/src/main/java/org/openmrs/module/mirebalais/MirebalaisConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
pom.xml

@mogoodrich , this is just configuring the ObsAcrossEncounters widget on the Clinician Dashboard to display the clinical notes. I am still working on the editing page. Thanks!

UHM-5400, display clinical notes on the dashboard

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

https://github.com/PIH/openmrs-module-pihcore/pull/309

Add consult initial form

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java
api/src/main/java/org/openmrs/module/mirebalais/require/RequireUtil.java

https://pihemr.atlassian.net/browse/UHM-5851

UHM-5851 Should only be possible to fill out intake form once

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderConstants.java
api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

Depends on https://github.com/PIH/openmrs-module-pihcore/pull/325 and https://github.com/PIH/openmrs-config-ses/pull/48

Add peru prescription configuration

---

api/src/main/java/org/openmrs/module/mirebalais/apploader/CustomAppLoaderFactory.java

Remove merge visits
